; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

	TITLE	D:\dev\compiler\sandbox\vs-toasm\test.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT

PUBLIC	_a
PUBLIC	_b
_DATA	SEGMENT
COMM	_aaaa:DWORD
_DATA	ENDS
_DATA	SEGMENT
_a	DD	FLAT:$SG1274
$SG1274	DB	'abaaa', 00H
	ORG $+2
_b	DD	FLAT:$SG1276
$SG1276	DB	'ab', 00H
_DATA	ENDS
END
