; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

	TITLE	D:\dev\compiler\sandbox\vs-toasm\test.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT

_DATA	SEGMENT
COMM	_a:BYTE:030H
COMM	_b:BYTE:030H
_DATA	ENDS
PUBLIC	_main
; Function compile flags: /Odsp
_TEXT	SEGMENT
_main	PROC
; File d:\dev\compiler\sandbox\vs-toasm\test.cpp
; Line 236
	push	ebp
	mov	ebp, esp
	push	esi
	push	edi
; Line 237
	push	12					; 0000000cH
	pop	ecx
	mov	esi, OFFSET _b
	mov	edi, OFFSET _a
	rep movsd
; Line 238
	xor	eax, eax
	pop	edi
	pop	esi
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
