; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

	TITLE	D:\dev\compiler\sandbox\vs-toasm\test.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT

PUBLIC	_foo
PUBLIC	_fooarr
_DATA	SEGMENT
_foo	DB	01H
	ORG $+3
	DD	02H
_fooarr	DB	01H
	ORG $+3
	DD	02H
	ORG $+24
_DATA	ENDS
END
