; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

    TITLE   D:\dev\compiler\test-asm\vs-toasm\test.cpp
    .686P
    .XMM
    include listing.inc
    .model  flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC  ?gc@@3PADA                  ; gc
CONST   SEGMENT
$SG3746 DB  'global-const', 00H
    ORG $+3
$SG3759 DB  'local-const', 00H
$SG3762 DB  '%s', 0aH, 00H
CONST   ENDS
_DATA   SEGMENT
?gc@@3PADA DD   FLAT:$SG3746                ; gc
_DATA   ENDS
PUBLIC  ?g@@YA_NXZ                  ; g
PUBLIC  ?f@@YA_JXZ                  ; f
PUBLIC  _main
EXTRN   _printf:PROC
; Function compile flags: /Odtp
_TEXT   SEGMENT
_d$ = -16                       ; size = 8
_a$ = -8                        ; size = 4
_lc$ = -4                       ; size = 4
_main   PROC
; File d:\dev\compiler\test-asm\vs-toasm\test.cpp
; Line 31
    push    ebp
    mov ebp, esp
    sub esp, 16                 ; 00000010H
; Line 32
    mov DWORD PTR _lc$[ebp], OFFSET $SG3759
; Line 34
    mov DWORD PTR _a$[ebp], 2
; Line 35
    call    ?f@@YA_JXZ              ; f
    mov DWORD PTR _d$[ebp], eax
    mov DWORD PTR _d$[ebp+4], edx
; Line 36
    mov eax, DWORD PTR ?gc@@3PADA       ; gc
    push    eax
    push    OFFSET $SG3762
    call    _printf
    add esp, 8
; Line 37
    mov eax, 3
; Line 38
    mov esp, ebp
    pop ebp
    ret 0
_main   ENDP
_TEXT   ENDS
; Function compile flags: /Odtp
_TEXT   SEGMENT
_h$1 = -16                      ; size = 4
_g$2 = -12                      ; size = 4
_b$ = -8                        ; size = 4
_e$3 = -4                       ; size = 4
?f@@YA_JXZ PROC                     ; f
; File d:\dev\compiler\test-asm\vs-toasm\test.cpp
; Line 11
    push    ebp
    mov ebp, esp
    sub esp, 16                 ; 00000010H
; Line 13
    mov DWORD PTR _b$[ebp], 4
; Line 14
    call    ?g@@YA_NXZ              ; g
    movzx   eax, al
    test    eax, eax
    je  SHORT $LN1@f
; Line 17
    mov ecx, DWORD PTR _e$3[ebp]
    add ecx, 1
    mov DWORD PTR _e$3[ebp], ecx
$LN1@f:
; Line 21
    mov DWORD PTR _g$2[ebp], 66         ; 00000042H
; Line 24
    mov DWORD PTR _h$1[ebp], 55         ; 00000037H
; Line 27
    mov eax, DWORD PTR _b$[ebp]
    cdq
; Line 28
    mov esp, ebp
    pop ebp
    ret 0
?f@@YA_JXZ ENDP                     ; f
_TEXT   ENDS
; Function compile flags: /Odtp
_TEXT   SEGMENT
?g@@YA_NXZ PROC                     ; g
; File d:\dev\compiler\test-asm\vs-toasm\test.cpp
; Line 6
    push    ebp
    mov ebp, esp
; Line 7
    mov al, 1
; Line 8
    pop ebp
    ret 0
?g@@YA_NXZ ENDP                     ; g
_TEXT   ENDS
END
